### ISSUE TITLE
Where is the download ?

### ISSUE THREAD

**Issue by Kuinox** [Skyppid/Array-Visualizer#1]
Sorry if this a stupid question but,  
I search for the .vsix installer, and i dont found the Download section you mentionned in the Readme:  

> Either go to Downloads and just get the latest .vsix-Installer

Actually i can't build this project myself because i don't have enough space on my laptop to install the needed dependencies.  
Thanks !

**Comment by Skyppid** [comment]
Sorry I somehow didn't get notified of your issue. You find it in the [release ](https://github.com/Skyppid/Array-Visualizer/releases)section on GitHub.
