### ISSUE TITLE
Where is the installer?

### ISSUE THREAD

**Issue by azadeh-sharafi** [Skyppid/Array-Visualizer#2]
Sorry if this is stupid question, i am new to github
I downloaded the release zip file and it look the same as cloning. There are the codes no .vsix installer???

I tried to build the solution and got this error:
Unable to locate ..\.nuget\nuget.exe

Would you please help me?

**Comment by strangelyslowduck** [comment]
@azadeh-sharafi it's in the releases section. [Here](https://github.com/Skyppid/Array-Visualizer/releases)
