### ISSUE TITLE
Can't install 1.6.0 on VS 2019 

### ISSUE THREAD

**Issue by raldo666** [Skyppid/Array-Visualizer#4]
Hi!

I attempted to install v 1.6.0 on my win10 machine.  The VS version is 16.5.1 enterprise.

at the end of the install I'm getting a message "the extension cannot be installed to this product due to prerequisites that cannot be resolved."

Any clues to what this could be? 

![image](https://user-images.githubusercontent.com/56290346/101020372-b12b1f00-356e-11eb-83c5-cf7b3062434a.png)

**Comment by rj1024** [comment]
> Hi!
> 
> I attempted to install v 1.6.0 on my win10 machine. The VS version is 16.5.1 enterprise.
> 
> at the end of the install I'm getting a message "the extension cannot be installed to this product due to prerequisites that cannot be resolved."
> 
> Any clues to what this could be?
> 
> ![image](https://user-images.githubusercontent.com/56290346/101020372-b12b1f00-356e-11eb-83c5-cf7b3062434a.png)

I have the same issue.

**Comment by Skyppid** [comment]
Sorry for the late reply. As of now the prerequisites are: Visual Studio MPF 11.0 or higher and .NET Framework 4.7.2 or higher.
Do you have those installed? MPF should be included in VS anyway but I assume you might not have the correct framework version?

EDIT: I released a new [version](https://github.com/Skyppid/Array-Visualizer/releases/tag/release-1.6.1), please try this one. There were some prereqs and dependencies which probably were from older versions and thus failed installation.

**Comment by rj1024** [comment]
> Sorry for the late reply. As of now the prerequisites are: Visual Studio MPF 11.0 or higher and .NET Framework 4.7.2 or higher.
> Do you have those installed? MPF should be included in VS anyway but I assume you might not have the correct framework version?
> 
> EDIT: I released a new [version](https://github.com/Skyppid/Array-Visualizer/releases/tag/release-1.6.1), please try this one. There were some prereqs and dependencies which probably were from older versions and thus failed installation.

Sorry for the rate reply from my side too,
But i did try your latest version and yes it is working like charm. Thanks a ton.
